<?php

return [
    'PER_PAGE' => 15,
    'BOOKING_MONTHLY_TARGET' => 20000,
    'BOOKING_WEEKLY_TARGET' => 4000,
    'BOOKING_QUARTERLY_TARGET' => 60000,
    'TODO_WEEKLY_TARGET' => 6000,
    'FLOAT_PRECISION' => 2,
];
